<font size="5">Importing tweepy Library</font>

In [85]:
import tweepy

<font size="5">Filling the credential obtained from twitter</font>

In [86]:
consumer_key = "" 
consumer_secret = ""
access_key = ""
access_secret = ""

<font size="4">In the below box we declare a function get_all_tweets which fetch all the tweets(maximum of 3240) from the account user_id. 
user_id is the only parameter of the function which accepts the twitter user id from which data has to be fetched.
This function return the information fetched by the tweepy library.</font>

In [87]:
def get_all_tweets(user_id = '@midasIIITD'):
    
    # Authorization to consumer key and consumer secret     
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    # Access to user's access key and access secret
    auth.set_access_token(access_key, access_secret)
    # Calling api
    api = tweepy.API(auth)

    #Initialize a list to hold all the Tweets
    alltweets = []  

    #Make initial request for most recent tweets (200 is the maximum allowed count)
    new_tweets = api.user_timeline(screen_name = user_id,count=200,tweet_mode = 'extended')

    #Saving the most recent tweets
    alltweets.extend(new_tweets)

    #Saving the id of the oldest tweet less one
    oldest = alltweets[-1].id - 1

    #Keep grabbing tweets until there are no tweets left to grab
    while len(new_tweets) > 0:
        print (f"getting tweets before {oldest}")

        #All subsiquent requests use the max_id param to prevent duplicates
        new_tweets = api.user_timeline(screen_name = user_id,count=200,max_id=oldest,tweet_mode = 'extended')

        #Save most recent tweets
        alltweets.extend(new_tweets)

        #Updating the id of the oldest tweet less one
        oldest = alltweets[-1].id - 1

        print (f"...{len(alltweets)} tweets downloaded so far")
    
    return alltweets

<font size="4">Calling the function get_all_tweets and storing the output of the function in a variable all_tweets.</font>

In [88]:
all_tweets = get_all_tweets()

getting tweets before 1074710061958627327
...344 tweets downloaded so far
getting tweets before 1021377705084739583
...344 tweets downloaded so far

<font size="5">Printing a tweet response</font>

In [89]:
print(all_tweets[0])

Status(_api=<tweepy.api.API object at 0x7f85a2d3fa58>, _json={'created_at': 'Wed Apr 10 09:01:29 +0000 2019', 'id': 1115902611599822852, 'id_str': '1115902611599822852', 'full_text': 'Clarification: Our earlier post which indicates that the interview has been done is referring to the interviews of the candidates who have submitted applications and tasks in the first round (not through IIITD internship portal). The second round candidates yet to be interviewed.', 'truncated': False, 'display_text_range': [0, 280], 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []}, 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 1021355762575073281, 'id_str': '1021355762575073281', 'name': 'MIDAS IIITD', 'screen_name': 'midasIIITD', 'location': 'New Delhi, India', 'description': 'MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.', 'url': 'https://t.co/Uwg7oSM6mE', 'entities': {'url': {'urls': [{'url': 'https://t.co/Uwg7oSM6mE', 'expanded_url': 'http://midas.iiitd.edu.in/', 'display_url': 'midas.iiitd.edu.in', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 295, 'friends_count': 43, 'listed_count': 0, 'created_at': 'Mon Jul 23 11:26:04 +0000 2018', 'favourites_count': 143, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 344, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1021355762575073281/1554320878', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True, 'default_profile_image': False, 'following': True, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en'}, created_at=datetime.datetime(2019, 4, 10, 9, 1, 29), id=1115902611599822852, id_str='1115902611599822852', full_text='Clarification: Our earlier post which indicates that the interview has been done is referring to the interviews of the candidates who have submitted applications and tasks in the first round (not through IIITD internship portal). The second round candidates yet to be interviewed.', truncated=False, display_text_range=[0, 280], entities={'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []}, source='Twitter Web Client', source_url='http://twitter.com', in_reply_to_status_id=None, in_reply_to_status_id_str=None, in_reply_to_user_id=None, in_reply_to_user_id_str=None, in_reply_to_screen_name=None, author=User(_api=<tweepy.api.API object at 0x7f85a2d3fa58>, _json={'id': 1021355762575073281, 'id_str': '1021355762575073281', 'name': 'MIDAS IIITD', 'screen_name': 'midasIIITD', 'location': 'New Delhi, India', 'description': 'MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.', 'url': 'https://t.co/Uwg7oSM6mE', 'entities': {'url': {'urls': [{'url': 'https://t.co/Uwg7oSM6mE', 'expanded_url': 'http://midas.iiitd.edu.in/', 'display_url': 'midas.iiitd.edu.in', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 295, 'friends_count': 43, 'listed_count': 0, 'created_at': 'Mon Jul 23 11:26:04 +0000 2018', 'favourites_count': 143, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 344, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1021355762575073281/1554320878', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True, 'default_profile_image': False, 'following': True, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, id=1021355762575073281, id_str='1021355762575073281', name='MIDAS IIITD', screen_name='midasIIITD', location='New Delhi, India', description='MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.', url='https://t.co/Uwg7oSM6mE', entities={'url': {'urls': [{'url': 'https://t.co/Uwg7oSM6mE', 'expanded_url': 'http://midas.iiitd.edu.in/', 'display_url': 'midas.iiitd.edu.in', 'indices': [0, 23]}]}, 'description': {'urls': []}}, protected=False, followers_count=295, friends_count=43, listed_count=0, created_at=datetime.datetime(2018, 7, 23, 11, 26, 4), favourites_count=143, utc_offset=None, time_zone=None, geo_enabled=False, verified=False, statuses_count=344, lang='en', contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='F5F8FA', profile_background_image_url=None, profile_background_image_url_https=None, profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', profile_banner_url='https://pbs.twimg.com/profile_banners/1021355762575073281/1554320878', profile_link_color='1DA1F2', profile_sidebar_border_color='C0DEED', profile_sidebar_fill_color='DDEEF6', profile_text_color='333333', profile_use_background_image=True, has_extended_profile=False, default_profile=True, default_profile_image=False, following=True, follow_request_sent=False, notifications=False, translator_type='none'), user=User(_api=<tweepy.api.API object at 0x7f85a2d3fa58>, _json={'id': 1021355762575073281, 'id_str': '1021355762575073281', 'name': 'MIDAS IIITD', 'screen_name': 'midasIIITD', 'location': 'New Delhi, India', 'description': 'MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.', 'url': 'https://t.co/Uwg7oSM6mE', 'entities': {'url': {'urls': [{'url': 'https://t.co/Uwg7oSM6mE', 'expanded_url': 'http://midas.iiitd.edu.in/', 'display_url': 'midas.iiitd.edu.in', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 295, 'friends_count': 43, 'listed_count': 0, 'created_at': 'Mon Jul 23 11:26:04 +0000 2018', 'favourites_count': 143, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 344, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1021355762575073281/1554320878', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True, 'default_profile_image': False, 'following': True, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, id=1021355762575073281, id_str='1021355762575073281', name='MIDAS IIITD', screen_name='midasIIITD', location='New Delhi, India', description='MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.', url='https://t.co/Uwg7oSM6mE', entities={'url': {'urls': [{'url': 'https://t.co/Uwg7oSM6mE', 'expanded_url': 'http://midas.iiitd.edu.in/', 'display_url': 'midas.iiitd.edu.in', 'indices': [0, 23]}]}, 'description': {'urls': []}}, protected=False, followers_count=295, friends_count=43, listed_count=0, created_at=datetime.datetime(2018, 7, 23, 11, 26, 4), favourites_count=143, utc_offset=None, time_zone=None, geo_enabled=False, verified=False, statuses_count=344, lang='en', contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='F5F8FA', profile_background_image_url=None, profile_background_image_url_https=None, profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', profile_banner_url='https://pbs.twimg.com/profile_banners/1021355762575073281/1554320878', profile_link_color='1DA1F2', profile_sidebar_border_color='C0DEED', profile_sidebar_fill_color='DDEEF6', profile_text_color='333333', profile_use_background_image=True, has_extended_profile=False, default_profile=True, default_profile_image=False, following=True, follow_request_sent=False, notifications=False, translator_type='none'), geo=None, coordinates=None, place=None, contributors=None, is_quote_status=False, retweet_count=0, favorite_count=0, favorited=False, retweeted=False, lang='en')

<font size="5">Number of response recieved</font>

In [90]:
print("Number of response : " +str(len(all_tweets)))

Number of response : 344

<font size="5">Initializing a list json_tweet to add all _json part of the tweets fetched</font>

In [91]:
json_tweet = []
for i in range(len(all_tweets)):
    json_tweet.append(all_tweets[i]._json)

<font size="5">Dumping all the response to JSON file json_file</font>

In [92]:
import json
json_file = json.dumps(json_tweet)

<font size="5">Saving a file to pc as output.jsoln</font>

In [101]:
import jsonlines
with open('output.jsoln','w') as outfile:
        outfile.write(json_file)

outfile.close()

<font size="5">Opening the above saved file as j_file</font>

In [233]:
j_file = jsonlines.open('output.jsoln')

<font size="5">Storing the required parameters to be shown in arrays</font>

In [234]:
#Initializing different lists
text = []
date_and_time = []
number_of_likes = []
number_of_retweets = []
number_of_image = []
#For all the tweet responses
for item in j_file.read():
    text.append(item["full_text"])
    date_and_time.append(item["created_at"])
    number_of_likes.append(item["favorite_count"])
    number_of_retweets.append(item["retweet_count"])
    if ('media' in item["entities"]):
        number_of_image.append(1)
    else:
        number_of_image.append(0)

<font size="5">Creating a pandas dataframe to show the datas in tabular form</font>

In [235]:
#Importing pandas library
import pandas as pd
#Creating dataframe
data = pd.DataFrame({"Text of Tweet":text,
              "Date and time of tweet":date_and_time,
              "Number of favorites/likes":number_of_likes,
              "Number of retweets":number_of_retweets,
              "Number of images in tweet":number_of_image})

<font size="5">Showing the data in tabular form</font>

In [236]:
data

,Text of Tweet,Date and time of tweet,Number of favorites/likes,Number of retweets,Number of images in tweet
0,Clarification: Our earlier post which indicate...,Wed Apr 10 09:01:29 +0000 2019,0,0,0
1,RT @IIITDelhi: Applications open for MTech (CB...,Wed Apr 10 04:51:26 +0000 2019,0,1,0
2,RT @IIITDelhi: We are delighted to share that ...,Tue Apr 09 16:45:07 +0000 2019,0,14,0
3,RT @Harvard: Professor Jelani Nelson founded A...,Tue Apr 09 05:04:27 +0000 2019,0,36,0
4,RT @emnlp2019: For anyone interested in submit...,Tue Apr 09 05:04:11 +0000 2019,0,17,0
5,RT @multimediaeval: Announcing the 2019 MediaE...,Mon Apr 08 19:38:09 +0000 2019,0,15,0
6,"Many Congratulations to @midasIIITD student, S...",Mon Apr 08 07:08:12 +0000 2019,18,2,1
7,@midasIIITD thanks all students who have appea...,Mon Apr 08 03:27:42 +0000 2019,5,0,1
8,"@himanchalchandr Meanwhile, complete CV/NLP ta...",Sun Apr 07 14:17:29 +0000 2019,0,0,0
9,@sayangdipto123 Submit as per the guideline ag...,Sun Apr 07 14:17:09 +0000 2019,0,0,0
10,We request all students whose interview are sc...,Sun Apr 07 11:43:24 +0000 2019,1,1,0
11,"Other queries: ""none of the Tweeter Apis give ...",Sun Apr 07 06:55:19 +0000 2019,5,2,0
12,"Other queries: ""do we have to make two differe...",Sun Apr 07 06:53:38 +0000 2019,5,1,0
13,"Other queries: ""If using Twitter api, it does ...",Sun Apr 07 05:32:27 +0000 2019,6,1,0
14,Response to some queries asked by students on ...,Sun Apr 07 05:29:40 +0000 2019,7,1,0
15,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,Sat Apr 06 17:11:29 +0000 2019,0,2,0
16,@nupur_baghel @PennDATS Congratulation @nupur_...,Sat Apr 06 16:43:27 +0000 2019,18,3,1
17,We have emailed the task details to all candid...,Fri Apr 05 16:08:37 +0000 2019,11,1,0
18,RT @rfpvjr: Our NAACL paper on polarization in...,Fri Apr 05 04:05:11 +0000 2019,0,16,0
19,RT @kdnuggets: Effective Transfer Learning For...,Fri Apr 05 04:04:43 +0000 2019,0,11,1
20,RT @stanfordnlp: What’s new in @Stanford CS224...,Wed Apr 03 18:31:53 +0000 2019,0,59,0
21,RT @DeepMindAI: Today we're releasing a large-...,Wed Apr 03 17:04:32 +0000 2019,0,873,0
22,RT @ylecun: Congratulations Jitendra Malik !\n...,Wed Apr 03 09:03:40 +0000 2019,0,16,0
23,RT @IIITDelhi: Another chance to take admissio...,Wed Apr 03 07:46:02 +0000 2019,0,4,0
24,Dear @midasIIITD internship candidates who hav...,Tue Apr 02 04:20:13 +0000 2019,8,1,0
25,Looking forward to your paper submission to @I...,Tue Apr 02 02:44:54 +0000 2019,5,1,0
26,RT @ngrams: Reproducibility in multimedia rese...,Tue Apr 02 02:35:44 +0000 2019,0,7,0
27,Online application for https://t.co/DJFDrQsHZP...,Mon Apr 01 06:53:08 +0000 2019,7,2,0
28,RT @ACMMM19: A final reminder of the Reproduci...,Sun Mar 31 10:21:24 +0000 2019,0,10,0
29,RT @isarth23: Thanks for the support and help ...,Fri Mar 29 19:43:24 +0000 2019,0,2,0
...,...,...,...,...,...
314,RT @TensorFlow: TensorFlow 1.10.0 has been rel...,Thu Aug 09 05:59:57 +0000 2018,0,265,0
315,@midasIIITD is looking for motivated IIITD MTe...,Wed Aug 08 11:30:56 +0000 2018,2,1,0
316,@IIITDelhi @ponguru @RatnRajiv The results of ...,Wed Aug 08 05:53:48 +0000 2018,3,1,1
317,RT @IIITDelhi: @midasIIITD has secured rank 1 ...,Wed Aug 08 05:45:58 +0000 2018,0,1,0
318,RT @kdnuggets: Comparison of Top 6 Python NLP ...,Tue Aug 07 07:16:33 +0000 2018,0,40,1
319,Check more details of the 20th IEEE Internatio...,Tue Aug 07 02:05:12 +0000 2018,1,1,0
320,MR2AMC@ISM 2018 will be organized by @RatnRaji...,Tue Aug 07 01:58:49 +0000 2018,1,1,0
321,"Our workshop proposal named, ""MR2AMC: Multimod...",Tue Aug 07 01:50:33 +0000 2018,1,1,0
322,@NUSComputing Congratulations Abdelhak and Pro...,Mon Aug 06 17:48:23 +0000 2018,0,0,0
323,RT @goodfellow_ian: One of the most anticipate...,Mon Aug 06 17:46:59 +0000 2018,0,103,1
324,@the_dhumketu Great to have you in @midasIIITD,Mon Aug 06 06:06:47 +0000 2018,0,0,0
325,Congratulation @soujanyaporia for being appoin...,Fri Aug 03 05:56:33 +0000 2018,6,1,0
326,@IIITDelhi @the_dhumketu Thanks team @midasIII...,Wed Aug 01 11:47:15 +0000 2018,5,1,1
327,RT @IIITDelhi: Congratulations @midasIIITD int...,Wed Aug 01 11:20:07 +0000 2018,0,4,0
328,RT @learning_pt: Profile of the 5 Indian under...,Wed Aug 01 05:06:47 +0000 2018,0,4,0
329,Have a look at the list of accepted papers in ...,Tue Jul 31 12:11:52 +0000 2018,1,0,0
330,RT @goodfellow_ian: https://t.co/hYiWI7ntyk Te...,Tue Jul 31 02:06:26 +0000 2018,0,264,0
331,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...,Mon Jul 30 07:30:51 +0000 2018,0,2,0
332,"RT @ylecun: Jitendra Malik, who directs FAIR-M...",Sat Jul 28 11:07:11 +0000 2018,0,57,0
333,RT @kdnuggets: .@Bloomberg launches free cours...,Sat Jul 28 06:14:09 +0000 2018,0,105,0
334,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...,Sat Jul 28 06:13:48 +0000 2018,0,7,0
335,RT @IIITDelhi: We are delighted to announce th...,Sat Jul 28 04:08:21 +0000 2018,0,6,0
336,Get ready for the annual technical fest of @II...,Fri Jul 27 06:46:44 +0000 2018,3,2,0
337,Congratulations Dr. @RatnRajiv and team @midas...,Fri Jul 27 04:07:31 +0000 2018,8,2,0
338,Congratulations MIDAS @midasIIITD intern Prakh...,Wed Jul 25 05:14:35 +0000 2018,5,1,0
339,MIDAS@IIITD foundation. https://t.co/LKuzyBHzjm,Tue Jul 24 10:33:23 +0000 2018,2,1,0
340,It feels great to be the part of @IIITDelhi. h...,Tue Jul 24 10:12:34 +0000 2018,2,1,0
341,"Thank you, @toonzratn for designing the logo o...",Tue Jul 24 09:46:26 +0000 2018,4,1,1
342,We are on Facebook too. Like our page to get o...,Mon Jul 23 16:25:05 +0000 2018,3,1,0
343,MIDAS is a group of researchers at IIIT-Delhi ...,Mon Jul 23 12:53:15 +0000 2018,7,4,0